Repository Weather-Together/weather1-fe, pull requests merged in 2024-02, with the labels that each got.

#10 Setup/components
  cypress/e2e/intial.cy.js
  package-lock.json
  package.json
  src/APICalls/APICalls.tsx
  src/App.css
  src/App.js
  src/App/App.css
  src/App/App.js
  src/App/App.test.js
  src/CompGame/CompGame.css
  src/CompGame/CompGame.tsx
  src/DailyGame/DailyGame.css
  src/DailyGame/DailyGame.js
  src/Header/Header.css
  src/Header/Header.tsx
  src/LandingPage/LandingPage.css
  src/LandingPage/LandingPage.js
  src/Login/Login.css
  src/Login/Login.tsx
  src/Map/Map.css
  src/Map/Map.js
  src/MockData/MockData.tsx
  src/NewUser/NewUser.css
  src/NewUser/NewUser.tsx
  src/UserProfile/UserProfile.css
  src/UserProfile/UserProfile.tsx
  src/index.js
  tsconfig.json
Labels: enhancement

#23 Function/login routing
  src/APICalls/APICalls.tsx
  src/App/App.tsx
  src/Images/logo_480.png
  src/LandingPage/LandingPage.js
  src/Login/Login.css
  src/Login/Login.tsx
  src/MockData/MockData.tsx
  src/NewUser/NewUser.css
  src/NewUser/NewUser.tsx
  src/react-app-env.d.ts
Labels: enhancement

#29 Login cypress testing
  cypress/e2e/login.cy.js
  cypress/fixtures/logo_480.png
  cypress/fixtures/mockUser.json
  cypress/support/commands.js
  src/Login/Login.tsx
Labels: Testing

#37 Change to localStorage for user
  cypress/downloads/downloads.html
  cypress/e2e/intial.cy.js
  cypress/support/commands.js
  package.json
  src/App/App.tsx
  src/Competitive/CompetitiveGame.js
  src/CreatePrivateGame/CreatePrivateGame.jsx
  src/DailyGame/DailyGame.tsx
  src/Dashboard/Dashboard.tsx
  src/Header2/Header2.tsx
  src/Login/Login.tsx
  src/NotFound/NotFound.js
Labels: enhancement

#45 Function/email verification
  src/App/App.tsx
  src/LandingPage/LandingPage.js
  src/Login/Login.tsx
  src/NewUser/NewUser.tsx
Labels: enhancement

#69 Feature/revisit private game views
  src/CreatePrivateGame/CreatePrivateGame.js
Labels: enhancement

#77 Change render URLs to heroku URLs
  cypress/e2e/competitive.cy.js
  cypress/e2e/dailyGame.cy.js
  cypress/e2e/dashboard.cy.js
  cypress/support/commands.js
  src/Competitive/CompetitiveGame.js
  src/CreatePrivateGame/CreatePrivateGame.js
  src/DailyGame/DailyGame.tsx
  src/Dashboard/Dashboard.tsx
  src/LandingPage/LandingPage.js
  src/Login/Login.tsx
  src/NewUser/NewUser.tsx
  src/Private/PrivateGameView.js
  src/PrivateGame/PrivateGame.js
Labels: enhancement

#76 Add username to display on header
  cypress/downloads/downloads.html
  cypress/fixtures/competitiveGameGet.json
  src/App/App.tsx
  src/Dashboard/Dashboard.tsx
  src/Header2/Header2.css
  src/Header2/Header2.tsx
Labels: enhancement

#75 Change username prompt in login field to email address
  cypress/e2e/login.cy.js
  src/Login/Login.tsx
Labels: enhancement

#83 Add success message upon successful registration
  src/NewUser/NewUser.css
  src/NewUser/NewUser.tsx
Labels: enhancement

#80 Ensure that all links are visible in nav bar for header
  src/App/App.tsx
  src/Competitive/CompetitiveGame.js
  src/Header2/Header2.css
Labels: bug

#85 Local Storage to prevent extra API-calls
  src/Competitive/CompetitiveGame.js
  src/DailyGame/DailyGame.tsx
  src/Dashboard/Dashboard.tsx
  tsconfig.json
Labels: enhancement

#95 Feature/scoring modal
  cypress/downloads/downloads.html
  cypress/e2e/dailyGame.cy.js
  src/DailyGame/DailyGame.css
  src/DailyGame/DailyGame.tsx
Labels: enhancement
